firstPresident = ["who is the first president", "who's the first president"]
repeat = ["repeat after me", "say this", "repeat", "repeat me", "say this for me", "say this phrase", "repeat this phrase"]
newTab = ["open a new tab", "create a new tab", "new tab", "make a new tab"]
stop = ["stop running", "stop", "don't talk to me", "shut up", "turn off", "off", "quiet", "end"]
calculate = ["what is ", "calculate"]
search = ["search the web for", "search google for", "search for", "search", "look up" ]
standby = ["go on stand by", "standby", "mute", "pause"]
exitStandby = ["exit standby", "unmute", "unpause"]